### ISSUE TITLE
[Discussion] which model to choose for the project 

### ISSUE THREAD

**Issue by afzal442** [jackabald/TiDB-Hack-NL-repo-search#13]
I think we can play around with the models from hackathon sponsors, and choose the right one to fit for the project use case.

Reference: https://tidbhackathon2024.devpost.com/updates/32137-tools-from-our-sponsors-for-your-hackathon-project

**Comment by afzal442** [comment]
https://ask.pingcap.com/t/development-tools-tidb-future-app-hackathon-2024/2112

**Comment by jackabald** [comment]
https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo/

https://docs.llamaindex.ai/en/stable/examples/vector_stores/TiDBVector/

https://docs.llamaindex.ai/en/stable/module_guides/indexing/vector_store_index/

**Comment by jackabald** [comment]
I am currently working with these three docs to try to migrate the project to llama in a new branch.

**Comment by afzal442** [comment]
Awesome. Let's hack every possible way.

**Comment by jackabald** [comment]
https://docs.pingcap.com/tidbcloud/vector-search-integrate-with-llamaindex

Adding for future use.

**Comment by afzal442** [comment]
hey @jackabald currently the jina api model is wanting credits over free. Or am I missing something while running the app?

**Comment by jackabald** [comment]
You are correct it happened to me too. You can go on jina.ai on your phone or other device and get a new API key and it will work again.

**Comment by afzal442** [comment]
Done!
