### ISSUE TITLE
Update the Frontend

### ISSUE THREAD

**Issue by jackabald** [jackabald/TiDB-Hack-NL-repo-search#15]
1. There should be a button or some sort of functionality to index the repository before the query, the repo should not be indexed everytime there's a query.
2. The frontend should allow for a more "chat like" experience rather than 1 question that's all.

**Comment by afzal442** [comment]
That's true. I observed that too. Will hack around this.

**Comment by jackabald** [comment]
https://docs.llamaindex.ai/en/latest/module_guides/deploying/query_engine/usage_pattern/ 

information on how to get a "streaming response," this will reduce wait times by printing out words as the LLM loads them. Additionally if we configure it right it will make our frontend look more like a chat bot. 

https://docs.streamlit.io/develop/tutorials/llms/build-conversational-apps

This is some streamlit tutorials for making a chat bot.

**Comment by afzal442** [comment]
Thanks I will look into it by tomorrow.

**Comment by afzal442** [comment]
Now the new UI supports the Chatbot feat, but the response is not format as per the query. Could you look into it and change the logic as per the project's goal?

![image](https://github.com/user-attachments/assets/45fdcb3b-f215-4046-b4ff-f4c54df0f0d5)

**Comment by jackabald** [comment]
![Screenshot from 2024-08-10 20-58-11](https://github.com/user-attachments/assets/4db638a6-002a-4460-a936-bed87145c5dd)
So it looks like it does have the functionality to return code snippets. But as you can see it clearly gets my first query wrong. I don't know if this is something that is directly fixable, I think playing around with different LLMs could possibly change results but I'm not really sure. Do you have any ideas?

**Comment by afzal442** [comment]
Thanks for testing that out. That means it's working fine.
> I think playing around with different LLMs could possibly change results but I'm not really sure. Do you have any ideas?

I think you are right. I have ideas but let's see if time permits, we will do that.

**Comment by afzal442** [comment]
Until then you can try out exploring like giving options to users to use DifyAI or LeptonAI models etc.

**Comment by jackabald** [comment]
I will explore the metadata filters and see if I can use them to improve results.

**Comment by jackabald** [comment]
https://www.youtube.com/watch?v=u5Vcrwpzoz8 

super interesting video relating to this topic.

**Comment by afzal442** [comment]
Completed
