### ISSUE TITLE
update embedding model

### ISSUE THREAD

**Issue by jackabald** [jackabald/TiDB-Hack-NL-repo-search#16]
We should try to use the Jina AI embedding tools as they are a hackathon sponsor.
`code_search.py` uses HuggingFace for embeddings, we should try to change that to Jina.

**Comment by afzal442** [comment]
I agree. As I said we can use whatever is suitable for the process.

**Comment by jackabald** [comment]
https://jina.ai/news/full-stack-rag-with-jina-embeddings-v2-and-llamaindex/


info on using jina with llamaIndex

**Comment by afzal442** [comment]
Wow. Thanks for sharing though.
