### ISSUE TITLE
Integrate Issues into indexing

### ISSUE THREAD

**Issue by jackabald** [jackabald/TiDB-Hack-NL-repo-search#20]
https://llamahub.ai/l/readers/llama-index-readers-github?from=

The Github reader package has readers for reading issues, collaborators, and repo files (currently we only have reading files implemented). We can try to incorporate issues into our model so that if someone queries about the issues in a repo it has access to them.

**Comment by afzal442** [comment]
That's interesting. Looks like _All three readers will require a personal access token (which you can generate under your account settings)_

**Comment by afzal442** [comment]
I encountered this below error while firing the query
```    if isinstance(self._bind, sqlalchemy.engine.Connection):
AttributeError: 'TiDBVectorClient' object has no attribute '_bind'
```

**Comment by afzal442** [comment]
sorry Jack, when you are free, have a look. why am I still facing this following issue?
```
got 3209 characters- adding to documents - tests/test_index_code.py
An error occurred: No module named 'MySQLdb'
Exception ignored in: <function TiDBVectorClient.__del__ at 0x7f5173606170>
Traceback (most recent call last):
  File "/TiDB-Hack-NL-repo-search/venv/lib/python3.10/site-packages/tidb_vector/integrations/vector_client.py", line 175, in __del__
    if isinstance(self._bind, sqlalchemy.engine.Connection):
AttributeError: 'TiDBVectorClient' object has no attribute '_bind'
```

**Comment by afzal442** [comment]
Why this line `could not parse ...` comes up in the log after I run the app with an i/p `https://github.com/jackabald/TiDB-Hack-NL-repo-search` and hit submit? Any way to ignore/hide this?
```
generating document for src/rag.py
could not parse src/rag.py as a supported file type - falling back to decoding as utf-8 raw text
got 2489 characters- adding to documents - src/r
```

**Comment by jackabald** [comment]
try installing the sql client:

``` bash
pip install mysqlclient
```
The `could not parse ...` is because the parser can't read .py files. However, It still reads the files as UTF-8 raw text, the code is still stored, and the LLM can still respond to questions about the code. I will try to find a way to suppress this warning.

**Comment by jackabald** [comment]
If you already have the sql client installed I would try to delete your repo and re-clone it? maybe there is something wrong with your environment?

**Comment by jackabald** [comment]
I just updated requirements.txt to include `mysqlclient`

**Comment by afzal442** [comment]
Thanks that fixed the issue, but you also need to set up OLLAMA api. Or is there any pre-setup?

**Comment by jackabald** [comment]
Yeah you are right, thank you for creating the Ollama doc it looks great!

**Comment by afzal442** [comment]
Closing as completed
