### ISSUE TITLE
Develop Search logic in `code_search.py`

### ISSUE THREAD

**Issue by jackabald** [jackabald/TiDB-Hack-NL-repo-search#3]
This module will handle the heavy lifting of searching through the vectorized code:

- Implement functions to interact with TiDB, perform vector searches, and return relevant code snippets.
- Integrate with OpenAI or another LLM provider to process natural language queries.

**Comment by afzal442** [comment]
I have an experience with gemini api as well which is a free though.

**Comment by jackabald** [comment]
I have minimal experience with either Gemini or openAI's dev tools, so I'm unsure which would better fit our needs. 

The goal of the project is to be able to take natural language that references a piece of code, and find the piece of code it references in a codebase of as many files as we want. 

e.x. "find the HTML div that holds all of the information related to etc ...."

   -> /this/is/a/file/path/to/the/html  - line 24 - 50. [short explanation about how this is the HTML div your looking for]

That's a general search query I want our final product to be able to produce. But I wonder if this is feasible. I have never used TiDB or any type of vector search, so I am still not 100% convinced this project is even achievable. And I don't know exactly what an LLM would even do for us. If you have any ideas, please let me know. I am going to really start putting some work into coding this weekend. I appreciate you for helping!

**Comment by afzal442** [comment]
Thanks for the context. I have used both the APIs and TIDB as well. But for
this project specific, I have to dig into it.

I can take this up. :)

**Comment by jackabald** [comment]
I think you may need some implementation of `index_code.py` to implement this fully. I've assigned you the issue and I will be studying TiDB to find some solutions myself.

Thank you and good luck!

**Comment by afzal442** [comment]
adding links for referrence
https://docs.pingcap.com/tidbcloud/vector-search-integrate-with-langchain

**Comment by jackabald** [comment]
hey @afzal442 ,
Your current implementation of code_search.py takes in file path and gets snippets from the files in the path. We already do that in `index_code.py` . `code_search.py` should 
1. get a vector representation of the user query.
2. retrieve the code vectors from TiDB (we don't want to make the code vectors in search because it will be super costly)
3. use vector search
4. display results (we will need to update these results to make them more chat like)
![Drawing sketchpad](https://github.com/user-attachments/assets/060cd45c-a61f-4fc7-bd92-dd4f81ad02ae)
This file is doing this part of the diagram. I am going to try to get started on it, this code is more difficult than `index_code.py` i think imo.

**Comment by afzal442** [comment]
That makes sense. I will try to complete the TODO since I have got the
process from the example.

**Comment by afzal442** [comment]
now, there has been issue in the logic of code snippet search, I am not sure where exactly. here is following video clip to reproduce.

https://github.com/user-attachments/assets/571df434-c2be-478c-9a9e-309fee48bb70

**Comment by afzal442** [comment]
I think a little workaround and hacking will do the job.
