### ISSUE TITLE
create the frontend

### ISSUE THREAD

**Issue by jackabald** [jackabald/TiDB-Hack-NL-repo-search#4]
write now the frontend is in `templates/` and `static/` .

If you are a frontend dev,  feel free to use different technologies like tailwind or react depending on how you envision this frontend looking. 

Basic Structure:
- A search bar for user queries.
- A results section that displays file paths, line numbers, and code snippets.

**Comment by afzal442** [comment]
We can use streamlit framework

**Comment by jackabald** [comment]
@afzal442 One issue with Streamlit that I just found out is that it doesn't have a file uploader that allows users to upload directories. It only has a file uploader to upload certain files. One workaround we can use for right now is forcing projects to be zipped before uploading them, but we may want to find a better workaround in the future instead of forcing users to zip their project.

**Comment by afzal442** [comment]
got that. did you try streamlit framework? let's catch up today if you are available today as discussed.
