### ISSUE TITLE
Need further info for index_search

### ISSUE THREAD

**Issue by afzal442** [jackabald/TiDB-Hack-NL-repo-search#8]
I couldn't get the following o/p

```
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by afzal442** [comment]
Any motivation around the logic? Any referrence?

**Comment by jackabald** [comment]
I'm not really sure what you asking,

```
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
This is a warning and graphcodeBert comes with a pre-trained model that you can read about here: [](https://arxiv.org/abs/2009.08366)

As to the motivation around the logic or references: [](https://docs.pingcap.com/tidbcloud/vector-search-overview
)
This is the vector search docs, I would highly recommend looking at this for information about embeddings/vectors within TiDB
![Screenshot from 2024-08-03 14-16-36]
This vector search feature is necessary for our project given the TiDB hackathon project requirements.

**Comment by jackabald** [comment]
I'm not really sure what you asking,

Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

This is a warning and graphcodeBert comes with a pre-trained model that you can read about here:

As to the motivation around the logic or references:
This is the vector search docs, I would highly recommend looking at this for information about embeddings/vectors within TiDB

![Screenshot from 2024-08-03 14-16-36](https://github.com/user-attachments/assets/1ff58605-606f-4cf6-85f9-8ec40d69f38f)

This vector search feature is necessary for our project given the TiDB hackathon project requirements.

**Comment by jackabald** [comment]
I'm not really sure what you asking,
```
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
This is a warning and graphcodeBert comes with a pre-trained model that you can read about here: https://arxiv.org/abs/2009.08366
)
As to the motivation around the logic or references: https://docs.pingcap.com/tidbcloud/vector-search-overview
This is the vector search docs, I would highly recommend looking at this for information about embeddings/vectors within TiDB

![Screenshot from 2024-08-03 14-16-36](https://github.com/user-attachments/assets/1ff58605-606f-4cf6-85f9-8ec40d69f38f)

This vector search feature is necessary for our project given the TiDB hackathon project requirements.

**Comment by afzal442** [comment]
adding links for further study
https://github.com/pingcap/docs/blob/release-7.5/tidb-cloud/vector-search-get-started-using-python.md

**Comment by afzal442** [comment]
Closing as completed
